model_path: "/scratch/jw4209/hfmodels/gpt2"
model_name: "gpt2"
epochs: 600000
batch_size: 36
block_size: 1024
lr: 0.0001
betas: [0.9, 0.95]
dtype: "float16"
weight_decay: 0.1
seed: 0
eval_interval: 200
grad_clip: 1.0
peft: False